// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://arojkvbpebarpaffbmhl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyb2prdmJwZWJhcnBhZmZibWhsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4Mjg1MjgsImV4cCI6MjA2MDQwNDUyOH0.T8CCMK5AQWYslmeWYvd6O7P6z-uuQX_HJRrzFoUFzps";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);